trigger:
- master

jobs:
- job: publish
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - script: |
      python -m pip install --upgrade pip
      pip install poetry
      poetry install
    displayName: 'Install dependencies'
    
  - script: |
      pip install twine
    displayName: 'Install twine'
    
  - script: |
      poetry build
    displayName: 'build package'

  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: '{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}'
      
  - script: |
      python -m twine upload -r {{cookiecutter.project_slug}} --config-file $(PYPIRC_PATH) dist/*
    displayName: 'publish'
